/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch "Digital Heirloom" design system tokens
        'background':                '#fefcf4',
        'surface':                   '#fefcf4',
        'surface-bright':            '#fefcf4',
        'surface-dim':               '#e4e3d8',
        'surface-container':         '#f5f4eb',
        'surface-container-low':     '#fbf9f1',
        'surface-container-lowest':  '#ffffff',
        'surface-container-high':    '#efeee5',
        'surface-container-highest': '#e9e9de',
        'surface-variant':           '#e9e9de',
        'surface-tint':              '#ca0033',
        'primary':                   '#ca0033',
        'primary-container':         '#ff757b',
        'primary-dim':               '#b3002c',
        'primary-fixed':             '#ff757b',
        'primary-fixed-dim':         '#ff5866',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#4e000e',
        'on-primary-fixed':          '#000000',
        'on-primary-fixed-variant':  '#600013',
        'inverse-primary':           '#ff5261',
        'secondary':                 '#995200',
        'secondary-container':       '#ffc69a',
        'secondary-dim':             '#874800',
        'secondary-fixed':           '#ffc69a',
        'secondary-fixed-dim':       '#ffb375',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#6f3a00',
        'on-secondary-fixed':        '#532a00',
        'on-secondary-fixed-variant':'#7c4100',
        'tertiary':                  '#7b6100',
        'tertiary-container':        '#f5ce53',
        'tertiary-dim':              '#6c5600',
        'tertiary-fixed':            '#f5ce53',
        'tertiary-fixed-dim':        '#e6c047',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#584500',
        'on-tertiary-fixed':         '#413200',
        'on-tertiary-fixed-variant': '#634e00',
        'error':                     '#be2d06',
        'error-container':           '#f95630',
        'error-dim':                 '#b92902',
        'on-error':                  '#ffffff',
        'on-error-container':        '#520c00',
        'on-background':             '#383833',
        'on-surface':                '#383833',
        'on-surface-variant':        '#65655f',
        'outline':                   '#81817a',
        'outline-variant':           '#bab9b2',
        'inverse-surface':           '#0e0f0a',
        'inverse-on-surface':        '#9e9d96',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',  // true pill shape for floating nav
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        sans:     ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
